name: 'Configuration Check'

on:
  pull_request:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'conf/*.toml'
      - 'docs/*.md'
      - 'src/**/*'
      - 'scripts/*'
      - '.github/workflows/config.yaml'
  push:
    branches:
      - develop
      - prod

jobs:
  conf_check:
    name: Configurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Pip Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('scripts/*-requirements.txt') }}

      - name: Run Check
        run: |
          # Dependencies
          python -m pip install --upgrade pip
          pip install -r scripts/check_conf-requirements.txt

          # Scripts
          python scripts/check_conf.py
